### ISSUE TITLE
permission to push a new branch

### ISSUE THREAD

**Issue by pbinkley** [CanadianLinkedDataInitiative/ITCompetenciesDocument#1]
@bilalkhalid , I've done a preliminary conversion of our Google Doc to Markdown, but Github won't let me push my branch to this repo so everyone can see it. Could you check the team permissions and see if you can let me in?

Thanks!

**Comment by pbinkley** [comment]
... probably because I hadn't accepted your invitation to join the organization until now. But I have accepted now, and it still won't let me push.

**Comment by bilalkhalid** [comment]
Hi @pbinkley. Sorry it took me a couple of days, but you should now have read/write access to the repository. Please test and let me know.

**Comment by pbinkley** [comment]
finally got back to this - it works! Thanks for the fix.
